# Generated by Django 4.0.4 on 2022-06-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloTickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
    ]
