# Generated by Django 4.0.4 on 2022-06-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloTickets', '0002_ciudades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadesd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ciudadesd',
                'managed': False,
            },
        ),
    ]
